service: serverless-puppeteer # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: title
          method: get
    layers:
      - {Ref: HeadlessLambdaLayer}

layers:
  headless:
    path: headless

